version: '2'
services:
  redis:
    image: redis
    restart: always
    volumes:
      - redis:/data
  superset:
    image: amancevice/superset:latest
    restart: always
    depends_on:
      - redis
    environment:
      MAPBOX_API_KEY: ${MAPBOX_API_KEY}
      SUPERSET_HOME: /etc/superset
      UPLOAD_FOLDER: /etc/superset/upload/
    ports:
      - "8088:8088"
    volumes:
      - ./superset_config.py:/etc/superset/superset_config.py
      - ./superset:/var/lib/superset
      - ./superset/upload/:/etc/superset/upload/
volumes:
  redis:
    external: false
